### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by fafner8** [krmanik/anki-tts#3]
Unfortunately the script broke today and there's no longer any audio in Anki. Hope it can be fixed (I contacted the guy who you credited for the original code and he said the library needs updating or something.)

**Comment by krmanik** [comment]
Hi, I have checked it, it seems need update. I will update it soon.

**Comment by fafner8** [comment]
Thanks, the TTS is working, but now the audio just keeps looping, i.e. when you review the next card it plays again the audio from all the previews cards...

**Comment by krmanik** [comment]
I have pushed the fix, but new issues is, it is hard stop the previous playing audio in next card, I will check for solution

**Comment by krmanik** [comment]
You need to change the `main` to `v1.0.0`

```diff
-<script type="module" src="https://cdn.jsdelivr.net/gh/krmanik/anki-tts@main/src/anki_tts.js"></script>
+<script type="module" src="https://cdn.jsdelivr.net/gh/krmanik/anki-tts@v1.0.0/src/anki_tts.js"></script>
```

So need replace, because cdn is cached and new updates are not showing

```
<script type="module" src="https://cdn.jsdelivr.net/gh/krmanik/anki-tts@v1.0.0/src/anki_tts.js"></script>
```

**Comment by fafner8** [comment]
I updated the link to 1.0.1 but unfortunately it didn't fix the issue, the audio is still looping :(

**Comment by krmanik** [comment]
Try with this tag

```
<script type="module" src="https://cdn.jsdelivr.net/npm/anki_tts@latest/src/anki_tts.js"></script>
```

**Comment by fafner8** [comment]
> Try with this tag
> 
> ```
> <script type="module" src="https://cdn.jsdelivr.net/npm/anki_tts@latest/src/anki_tts.js"></script>
> ```

Works perfectly now, thanks so much!!

**Comment by krmanik** [comment]
#### 1. Copy this to card template
```html
<script type="module" src="https://cdn.jsdelivr.net/gh/krmanik/anki-tts@main/src/anki_tts.js"></script>
```

#### 2. Copy and change the filed name

```html
<script>
    function playTts() {
        let text = '{{Front}}';   // <-----   change Front to field name in card template
        ttsPlay(text);            // uses whichever engine/voice is selected in Settings
    }
</script>
```

<img width="1778" height="760" alt="Image" src="https://github.com/user-attachments/assets/d82488de-8902-40f4-8b4d-725514329318" />



#### 3. Then click on settings icon to change the 

<img width="747" height="342" alt="Image" src="https://github.com/user-attachments/assets/83a6d662-f2a4-4995-b933-6919bc6dd0d8" />
